apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- hardcoded-credential-signature-in-env-var.yaml
- hardcoded-credential-vendor-shape-in-env-var.yaml
- opaque-value-in-credential-named-env-var.yaml
