#!/usr/bin/env bash
set -euo pipefail

repo_dir=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)

echo "[1/4] Restoring the permissive network state and clean mailbox..."
"$repo_dir/scripts/setup-demo.sh"

echo "[2/4] Removing all sender Jobs..."
oc -n external-sender delete job \
  external-html-sender external-callback-sender callback-html-sender \
  --ignore-not-found --wait=true >/dev/null 2>&1 || true

echo "[3/4] Resolving runtime alerts generated by the previous run and reset..."
"$repo_dir/scripts/resolve-demo-runtime-alerts.sh"

echo "[4/4] Verifying the clean receiver and network state..."
receiver_host=$(oc -n demo-webhook get route demo-webhook -o jsonpath='{.spec.host}')
[ "$(curl -kfsS "https://${receiver_host}/requests" | jq 'length')" -eq 0 ]
oc -n ai-email-demo get networkpolicy openclaw-egress-before >/dev/null
! oc -n ai-email-demo get networkpolicy openclaw-egress-after >/dev/null 2>&1
echo "Runtime use case reset: two normal emails, no sessions, no receiver evidence, permissive egress."
